# Generated by Django 6.0.1 on 2026-01-08 07:38

import builtins
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Ethnicities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step by step cooking instructions.')),
                ('prep_time', models.PositiveIntegerField(help_text='Preparation time in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('cook_time', models.PositiveIntegerField(help_text='Cooking time in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.PositiveIntegerField(default=4, help_text='Number of servings.', validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category')),
                ('ethnicity', models.ForeignKey(help_text='Yoruba, Igbo, Hausa, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.ethnicity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount Needed', max_digits=6)),
                ('unit', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('cup', 'Cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('handful', 'Handful'), ('wrap', 'Wrap'), ('seed', 'Seed'), ('cube', 'Cube'), ('bulb', 'Bulb'), ('pinch', 'Pinch'), ('to taste', 'To Taste'), ('as needed', 'As Needed')], max_length=20)),
                ('notes', models.CharField(blank=True, help_text='e.g., chopped, diced, softened', max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': [builtins.id],
            },
        ),
        migrations.CreateModel(
            name='RecipeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='recipes.recipe')),
            ],
            options={
                'ordering': [builtins.id],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='recipes_rec_title_9ebae8_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['ethnicity'], name='recipes_rec_ethnici_49a68c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='recipes_rec_categor_4c01e4_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
    ]
